### ISSUE TITLE
Zipkin example is not working

### ISSUE THREAD

**Issue by fpage** [micronaut-guides/micronaut-microservices-distributed-tracing-zipkin#2]
Hi,

I implemented the services manually from the guide did the eureka config and Zipkin stuff, but I came across some issues. The services are correctly registered in Eureka, but when I call the service I get a 404:

curl http://localhost:8080/books
{"_links":{"self":{"href":"/books","templated":false}},"message":"Page Not Found"}

I tried multiple things and decided to comment out the zipkin section in the application.yml and it worked. Obviously, I don't get anything in Zipkin in that case.

curl http://localhost:8080/books
[{"name":"Building Microservices"}]

I thought I did a mistake since I did everything manually so I decided to clone this repo and try the real example, but I get the same result. It only works when I remove the Zipkin configuration in application.yml.

**What is weird:**

- No error message, no exception and I see stuff in Zipkin after startup
- When I put a breakpoint in BookController constructor of bookrecommendation it is never triggered unless I remove zipkin config then it stops at the constructor at startup

**Other notes**
- runtime "io.micronaut:micronaut-discovery-client" is missing in bookcatalogue so it is not registering to Eureka
- I think it would be good to add Eureka config even though the example is using default values

Just came back from Oracle CodeOne conference where I heard of this framework. Looks pretty promising! :)

Regards,

/Francis

**Comment by fpage** [comment]
The same code example works without any problem with Jaeger so it really has something to do with Zipkin.

/Francis

**Comment by ilopmar** [comment]
Hi @fpage, I'm not able to reproduce the issue. I've clone again the guide into a new directory and executed the following:

```
$ cd micronaut-microservices-distributed-tracing-zipkin/complete
$ ./gradlew run --parallel

> Task :bookcatalogue:run
11:56:32.474 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 3516ms. Server Running: http://localhost:8081

> Task :bookinventory:run
11:56:32.708 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 3800ms. Server Running: http://localhost:8082

> Task :bookrecommendation:run
11:56:32.853 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 3833ms. Server Running: http://localhost:8080
```
Now in another terminal I run Zipkin:
```
$ docker run -p 9411:9411 openzipkin/zipkin
```

And then, in a new terminal I execute:
```
$ curl http://localhost:8080/books
[{"name":"Building Microservices"}]
```
And in Zipkin I can see the trace:
![image](https://user-images.githubusercontent.com/559192/47713714-3bd81c00-dc3b-11e8-8c24-75b8b02d23a4.png)

Can you please try again with these steps?

**Comment by fpage** [comment]
Hi @ilopmar,

I tried your steps and it worked (some face palms occurred). But, I think I found the issue (but not the solution yet).

Here's what I did yesterday:

1. Followed all your steps, but didn't look in Zipkin
2. Stop everything because I didn't see the services registered in Eureka
3. Configure Eureka in application.yml on every services because my Eureka is on port 9001
4. Noticed that bookcatalogue is missing the deps for discovery so added it to build.gradle
5. Start everything with ./gradlew run -parallel and I could see the services registered in Eureka
6. Run curl http://localhost:8080/books and get {"_links":{"self":{"href":"/books","templated":false}},"message":"Page Not Found"}

So it seems like when Eureka and Zipkin are configured, nothing works. The service discovery dependency (runtime "io.micronaut:micronaut-discovery-client") is present in 2 of the services. What is the default behavior when no service discovery is configured in application.yml?

Thanks,

/Francis

**Comment by fpage** [comment]
I just want to reiterate that the same steps I did (configure Eureka and all) worked just fine with Jaeger. Same code example, but replaced Zipkin deps with Jaeger deps with Eureka configured.

**Comment by ilopmar** [comment]
So this is not an issue with this guide but an issue with Zipkin and Eureka. Could you please open an issue in the main project https://github.com/micronaut-projects/micronaut-core/issues with a simple sample app the reproduces the issue.
Thanks.
